version: "3.0"

services:
  frontend:
    build:
      context: .
    volumes:
      - ./:/www
      - node_modules:/www/node_modules
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 4000:3000
    command: yarn start
volumes:
  node_modules: